PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?this WHERE {
	{
		SELECT (SAMPLE(?ore) AS ?this) WHERE {
			?ore dcterms:subject ?uri .
			?uri skos:prefLabel ?ignore .
		}
		GROUP BY ?uri
	}
}