PREFIX ore:     <http://www.openarchives.org/ore/terms/>
PREFIX nao:     <https://archief.nl/def/ontologie/>

# 197492 items

SELECT $this WHERE {
	$this a nao:Recordaggregatie ;
		ore:isAggregatedBy ?aggregator ;
		ore:aggregates ?uri_cho .
	?uri_cho a nao:Archiefeenheid .

	VALUES ?aggregator {
		<https://archief.nl/doc/2.10.62ntfoto>
		<https://archief.nl/doc/2.19.123ntfoto>
		<https://archief.nl/doc/2.20.46ntfoto>
		<https://archief.nl/doc/2.21.008.01ntfoto>
		<https://archief.nl/doc/2.21.284ntfoto>
		<https://archief.nl/doc/2.24.01.01ntfoto>
		<https://archief.nl/doc/2.24.01.02ntfoto>
		<https://archief.nl/doc/2.24.01.03ntfoto>
		<https://archief.nl/doc/2.24.01.04ntfoto>
		<https://archief.nl/doc/2.24.01.06ntfoto>
		<https://archief.nl/doc/2.24.01.07ntfoto>
		<https://archief.nl/doc/2.24.01.08ntfoto>
		<https://archief.nl/doc/2.24.01.09ntfoto>
	}
}