PREFIX ore:     <http://www.openarchives.org/ore/terms/>
PREFIX nao:     <https://archief.nl/def/ontologie/>

SELECT $this WHERE {
  $this a nao:Recordaggregatie ;
    ore:isAggregatedBy <https://archief.nl/doc/2.24.10.01ntfoto> ;
	ore:aggregates ?uri_cho .
  ?uri_cho a nao:Archiefeenheid .
}


#<https://archief.nl/doc/>
#<https://archief.nl/doc/>
#<https://archief.nl/doc/>
#<https://archief.nl/doc/>
#<https://archief.nl/doc/>
#<https://archief.nl/doc/>
#<https://archief.nl/doc/>
#<https://archief.nl/doc/>
#<https://archief.nl/doc/>
#<https://archief.nl/doc/>
#<https://archief.nl/doc/>
#<https://archief.nl/doc/>
#<https://archief.nl/doc/>
#<https://archief.nl/doc/>
#<https://archief.nl/doc/>
#<https://archief.nl/doc/>
#<https://archief.nl/doc/2.24.10.02ntfoto>
#<https://archief.nl/doc/2.24.11ntfoto>
#<https://archief.nl/doc/2.24.14.02ntfoto>
#<https://archief.nl/doc/2.24.15ntfoto>
#<https://archief.nl/doc/2.24.26ntfoto>
#<https://archief.nl/doc/7.000spaondntfoto>
