services:
    map:
        image: ghcr.io/netwerk-digitaal-erfgoed/ld-workbench:latest
        user: $UID:$GID
        volumes: 
            - ./${DATASET}:/pipelines
        entrypoint: []
        network_mode: "host"

    fuseki:
        image: fuseki
        build:
            context: ../jena-fuseki-docker-5.6.0
            dockerfile: Dockerfile
            args:
            - JENA_VERSION=5.6.0
            - JENA_UID=$UID
            - JENA_GID=$GID
        command: '--config=/pipelines/fuseki-config.ttl'
        ports:
            - "3030:3030"
        volumes:
            - ./${DATASET}:/pipelines

    tools:
        build: ../europeana-tools
        user: $UID:$GID
        volumes:
              - ./${DATASET}:/pipelines
              - ./generic:/generic
#        environment:             # uncomment these lines and adjust the setting when running into Out of Memory problems
#            - JVM_ARGS=-Xmx24G   # the default setting is 8Gb

# NEEDS more configuration, should be mount on root pipelines dir
#    s3cmd:
#        image: d3fk/s3cmd
#        volumes:
#              - ./${DATASET}:/s3
#              - .s3:/root
