services:
    map:
        image: ghcr.io/netwerk-digitaal-erfgoed/ld-workbench:latest
        volumes: 
            - ${DATASET}:/pipelines
        entrypoint: []
        network_mode: "host"
    
    sparql-server-getdata:
        image: adfreiburg/qlever:latest
        volumes:
            - ${DATASET}/qlever:/data
        entrypoint: [] 
        command: /bin/sh -c "cd /data; qlever get-data"

    sparql-server-index:
        image: adfreiburg/qlever:latest
        volumes:
            - ${DATASET}/qlever:/data
        entrypoint: [] 
        command: /bin/sh -c "cd /data; qlever index --overwrite-existing"

    sparql-server:
        image: adfreiburg/qlever:latest
        volumes:
            - ${DATASET}/qlever:/data
        ports:
            - "8890:8890"
        entrypoint: [] 
        user: ${USER}
        command: /bin/sh -c "cd /data; qlever start && tail -f /dev/null"

    europeana-tools:
        build: ../europeana-tools
        volumes:
              - ${DATASET}:/opt/data
              - ./shapes:/opt/shapes

    s3cmd:
        image: d3fk/s3cmd
        volumes:
              - ${DATASET}:/s3
              - .s3:/root
