PREFIX ore:     <http://www.openarchives.org/ore/terms/>
PREFIX nao:     <https://archief.nl/def/ontologie/>

SELECT $this WHERE {
	$this a nao:Recordaggregatie ;
		ore:isAggregatedBy ?aggregator ;
		ore:aggregates ?uri_cho .
	?uri_cho a nao:Archiefeenheid .
}